SELECT
  a.prediction AS a_s_prediction,
  COALESCE(b.user_id, b.user_pseudo_id) AS client_id,
  TIMESTAMP_ADD(b.event_timestamp, INTERVAL 1 MICROSECOND) AS inference_date
FROM
  `${mds_project_id}.marketing_ga4_v1_${mds_dataset_suffix}.latest_event_per_user_last_72_hours` b,
  `{{source_table}}` a
WHERE
  COALESCE(a.user_id, "") = COALESCE(b.user_id, "")
  AND a.user_pseudo_id = b.user_pseudo_id
  AND a.prediction IS NOT NULL
