-- Copyright 2023 Google LLC
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- https://cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-create-remote-model#locations_2
-- You can create remote models over Vertex AI models in all of the regions that support Generative AI APIS, and also in the US and EU multi-regions.
-- If you choose to use a TPU accelerator when performing supervised tuning of an LLM, you must run your query in the europe-west4 region. 
-- Your supervised tuning computations also occur in the europe-west4 region, because that's where TPU resources are located.

-- Create a {{endpoint_name}} model using a remote connection to {{region}}.{{connection_name}}
CREATE OR REPLACE MODEL `{{project_id}}.{{dataset}}.{{model_name}}`
REMOTE WITH CONNECTION `{{project_id}}.{{region}}.{{connection_name}}`
OPTIONS (ENDPOINT = '{{endpoint_name}}');